---
- name: Recuring cron job
  hosts: test
  tasks:
          - name: Schedule a Cron Job
            cron:
                    name: Crontab file exists
                    job: date >> ~/my_date_time
                    minute: "*/2"
                    hour: 9-16
                    weekday: 1-15
                    user: student
                    cron_file: add-date-time
                    state: present
...
