---
- name: create /etc/hosts
  hosts: all
  tasks:
          - name: Deploy template
            template:
                    src: templates/etc_hosts.j2
                    dest: /etc_hosts
                    owner: student
                    group: student
...
